### PR TITLE
ContactForm component

### LINKED ISSUE #21: Website contact form
Design a form for contacting the website managers.

### PR DESCRIPTION
**Pull request by yossef-khaled**
largeContactForm
smallContactForm

### CODE REVIEW

**Comment by yossef-khaled** [comment]
Check how the user message is saved by taking A look at the console.

**Comment by HazemGabr232** [comment]
brilliant !, just add user mail field, add it to the state object and we are done here.

**Review by HazemGabr232 — CHANGES_REQUESTED** [review]
brilliant !, just add user mail field, add it to the state object and we are done here.

**Review by mhashim6 — APPROVED** [review]
Bueno!

**Comment by yossef-khaled** [comment]
largeContactForm
smallContactForm

**Review by HazemGabr232 — APPROVED** [review]
Great!

**Pull request merged**
